#!/bin/bash

# TITLE: check_kernel
# AUTHOR: Boardleash (Derek)
# DATE: Wednesday, March 19 2025

# Pull kernel information from hosts on network.
# As of 25MAR2025, this script will only work with the '<MY SPECIFIC USER>'.
# This is local to my setup only though, so make necessary changes.
# Replace text within "<>" with appropriate information.

# Debug
#set -x

###############
# VARIABLES
#############

# Log file variable
logfile=/usr/local/bin/script.log

# Variable to store the array of hosts
hfile=("<YOUR HOST HERE>", "<YOUR HOST HERE>", "<YOUR HOST HERE>")

# Verify who the user is that is running this script and stop if it is incorrect user
printf "\n$(date "+%c"): Starting check_kernel script" | tee -a "$logfile"
if [ "$USER" != '<MY SPECIFIC USER HERE>' ]; then
  printf "\n$(date "+%c"): INVALID USER: EXITING" | tee -a "$logfile"
  exit 126
fi

# For loop with nested if/else statement to use the above array and ssh to the host
# and pull the kernel information
for host in "${hfile[@]}"; do
  chkconn=$(ping -c 2 -O "$host")
  if [ "$?" == 0 ]; then
    grabkern=$(ssh "$USER"@"$host" 'uname -r')
    printf "\n$(date "+%c"): "$host" KERNEL= "$grabkern"" | tee -a "$logfile"
  else
    printf "\n$(date "+%c"): "$host" is OFFLINE" | tee -a "$logfile"
  fi
done
printf "\n$(date "+%c"): Completed check_kernel script" | tee -a "$logfile"
printf "\n\n"

# EOF
