#!/bin/bash

# TITLE: check_connections
# AUTHOR: Boardleash (Derek)
# DATE: Wednesday, March 19 2025

# Check connectivty to hosts on the network.
# Replace text that is inside of "<>" with appropriate information.

# Debug
#set -x

###############
# VARIABLES
#############

# Log file variable
logfile=/usr/local/bin/script.log

# Variable to store the array of hosts
hfile=("<YOUR HOST HERE>", "<YOUR HOST HERE>", "<YOUR HOST HERE>")

# For loop with nested if/else statement to ping the above array and notify if online or not
printf "\n$(date "+%c"): Starting check_connections script" | tee -a "$logfile"
for host in "${hfile[@]}"; do
  chkconn=$(ping -c 2 -O "$host")
  if [ "$?" == 0 ]; then
    printf "\n$(date "+%c"): "$host" is ONLINE" | tee -a "$logfile"
  else
    printf "\n$(date "+%c"): "$host" is OFFLINE" | tee -a "$logfile"
  fi
done
printf "\n$(date "+%c"): Completed check_connections script" | tee -a "$logfile"
printf "\n\n"

# EOF
